# Generated by Django 5.0.3 on 2024-04-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie.category'),
        ),
    ]
