# Generated by Django 5.0.3 on 2024-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_hot_alter_movie_iframe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
