# Generated by Django 5.0.3 on 2024-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_is_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Seasonal', 'Seasonal')], default='Single', max_length=100),
        ),
    ]
