# Generated by Django 5.0.3 on 2024-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(to='movie.movie'),
        ),
    ]
