# Generated by Django 5.0.3 on 2024-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_cast_movie_cast_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(related_name='cast', to='movie.movie'),
        ),
    ]
