# Generated by Django 5.0.3 on 2024-04-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_cast_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='actor_img_url',
            new_name='img_url',
        ),
    ]
