# Generated by Django 5.0.3 on 2024-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_rename_actor_img_url_cast_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
