# Generated by Django 5.0.3 on 2024-04-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_season_episode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='Series',
        ),
    ]
