# Generated by Django 5.0.3 on 2024-04-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_rename_season_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='movie',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category_table',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie_table',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
