# Generated by Django 5.0.3 on 2024-04-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_remove_series_movie_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cast',
            table='cast_table',
        ),
    ]
