# Generated by Django 5.0.3 on 2024-04-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_alter_cast_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='cast',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
