# Generated by Django 5.0.3 on 2024-05-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
