# Generated by Django 5.0.3 on 2024-05-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_alter_episode_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.movie'),
        ),
    ]
