# Generated by Django 5.0.3 on 2024-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_alter_season_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
