# Generated by Django 5.0.3 on 2024-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_episode_description_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
